eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10322/eureka
  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create-drop    # 애플리케이션 시작 시 DB 초기화 (개발용)
    show-sql: true             # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true       # SQL 로그 예쁘게 출력
  h2:
    console:
      enabled: true            # H2 콘솔 접속 허용 (http://localhost:8080/h2-console)
      path: /h2-console

naver:
  book:
    base-url: https://openapi.naver.com/v1/search
    client-id: C8kYlyIf_05ozU5MMduV
    client-secret: W8TZKkfTBj
