# application-ci.yml
spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: dummy-ci-secret

management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    db:
      enabled: true
    redis:
      enabled: true


naver:
  book:
    base-url: https://openapi.naver.com/v1/search
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}

minio:
  endpoint: http://storage.java21.net:8000
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: dodream-book-images