# application-prod.yml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://dodream.shop:10322/eureka
  instance:
    prefer-ip-address: false
    hostname: dodream.shop

#redis 사용 시 (redisConfig 등록했으면 없어도 됨)
spring:
  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 305

naver:
  book:
    base-url: https://openapi.naver.com/v1/search
    client-id: C8kYlyIf_05ozU5MMduV
    client-secret: W8TZKkfTBj

upload:
  book-image-dir: /home/be10/be10-team2/uploads/images/books/