### 인덱싱 처리
POST http://localhost:8080/books/reindex

### 검색
GET http://localhost:8090/public/books/search?keyword=귀멸&sort=REVIEW


# curl "http://localhost:9200/books/_search?pretty"
GET http://s4.java21.net:9200/books/_search?pretty

###

