### 도서 카테고리 추가
POST http://localhost:8080/books/2/categories
Content-Type: application/json

{
  "ids": [1,2]
}

### 해당 도서의 카테고리 조회
GET http://localhost:8080/books/1/categories
Content-Type: application/json

### 해당 카테고리의 도서 조회
GET http://localhost:8080/categories/1/books
Content-Type: application/json


### 도서 카테고리 단일 정보 수정
PATCH http://localhost:8080/books/1/categories/1?new-category-id=2
Content-Type: application/jso

### 도서 카테고리 삭제
DELETE http://localhost:8080/books/1/categories
Content-Type: application/json

{
  "ids": [2]
}