### 도서 카테고리 추가
POST http://localhost:8080/admin/books/1/categories
Content-Type: application/json

{
  "categoryIds" : [2]
}

### 해당 도서의 카테고리 조회
GET http://localhost:8080/books/1/categories
Content-Type: application/json

### 해당 카테고리 도서 조회
GET http://localhost:8080/categories/1/books
Content-Type: application/json


### 도서 카테고리 단일 정보 수정
PATCH http://localhost:8080/admin/books/1/categories/2
Content-Type: application/json

{
  "categoryId" : 1
}

### 도서 카테고리 삭제
DELETE http://localhost:8080/admin/books/1/categories
Content-Type: application/json

{
  "categoryIds" : [3]
}