### 카테고리 등록
POST http://localhost:8080/categories
Content-Type: application/json

{
  "categoryName": "JAVA",
  "depth": 1,
  "parentId": null
}


### 전체 카테고리 조회
GET http://localhost:8080/public/categories
Accept: application/json


### 특정 카테고리 조회
GET http://localhost:8080/public/categories/2
Accept: application/json


### 특정 카테고리에 하위 카테고리 조회
GET http://localhost:8080/public/categories/2/children
Accept: application/json


### 특정 카테고리에 연관 카테고리 전체 조회
GET http://localhost:8080/public/categories/1/related
Accept: application/json


### 특정 깊이 카테고리 조회
GET http://localhost:8080/public/categories/1/depth
Accept: application/json


### 카테고리 수정
PUT http://localhost:8080/categories/3
Content-Type: application/json

{
  "categoryName": "프로그래밍4-1revert",
  "depth": 5,
  "parentId": 4
}



### 카테고리 삭제
DELETE http://localhost:8080/categories/3


