### 도서 카테고리 추가
POST http://localhost:8080/admin/books/{book-id}/categories
Content-Type: application/json

{
  "categoryIds" : [1,2,3]
}

### 해당 도서의 카테고리 조회
POST http://localhost:8080/admin/books/{book-id}/categories
Content-Type: application/json

### 해당 카테고리 도서 조회
POST http://localhost:8080/categories/{category-id}/books
Content-Type: application/json


### 도서 카테고리 정보 수정
POST http://localhost:8080/admin/books/{book-id}/categories
Content-Type: application/json

{
  "categoryIds" : [1,2,3]
}

### 도서 카테고리 삭제
POST http://localhost:8080/admin/books/{book-id}/categories/{category-id}
Content-Type: application/json
